/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MfeRouteImport } from './routes/mfe'
import { Route as IndexRouteImport } from './routes/index'

const MfeRoute = MfeRouteImport.update({
  id: '/mfe',
  path: '/mfe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mfe': typeof MfeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mfe': typeof MfeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mfe': typeof MfeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mfe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mfe'
  id: '__root__' | '/' | '/mfe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MfeRoute: typeof MfeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mfe': {
      id: '/mfe'
      path: '/mfe'
      fullPath: '/mfe'
      preLoaderRoute: typeof MfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MfeRoute: MfeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
