// This file is auto-generated by `tsr generate`. Do not edit manually.
// Run `pnpm --filter @repo/shell dev` to regenerate.
import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";
import { Route as MfeRoute } from "./routes/mfe";

const routeTree = rootRoute.addChildren([IndexRoute, MfeRoute]);

export { routeTree };
